name: build and push to container registry

on:   
  pull_request:
    paths:
      - '.github/**'
      - 'Dockerfile'
      - 'notejam/**'
      - '*.py'
      - '!test**'
      - '!**.rst'

env:
  REGISTRY: "ghcr.io/msaitz"
  IMAGE_NAME: "notejam"
  IMAGE_VERSION: "0.1.0-beta"
  
jobs:
  test:
   runs-on: ubuntu-latest
   container:
     image: python:2.7-alpine
   steps:
     - uses: actions/checkout@v2
     - name: Install dependencies
       run: pip install -r requirements.txt
     - name: Run tests
       run: python tests.py

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
