name: test project

on:   
  pull_request:
    paths:
      - '.github/**'
      - 'Dockerfile'
      - 'notejam/**'
      - '*.py'
      - '!**.rst'
  push:
    branches-ignore:
      - master
    paths:
      - '.github/**'
      - 'Dockerfile'
      - 'notejam/**'
      - '*.py'
      - '!**.rst'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: notejam 
      - name: Run tests
        run: docker run notejam python tests.py
