name: test project

on:   
  push:
    branches:
      - master
    paths:
      - '.github/**'
      - 'Dockerfile'
      - 'notejam/**'
      - '*.py'
      - '!**.rst'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:2.7-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python tests.py
