name: test project

on:   
  pull_request:
    paths:
      - '.github/**'
      - 'Dockerfile'
      - 'notejam/**'
      - '*.py'
      - '!**.rst'
  push:
    paths:
      - '.github/**'
      - 'Dockerfile'
      - 'notejam/**'
      - '*.py'
      - '!**.rst'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:2.7-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python tests.py
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
